#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
os: WMF 5
version: 0.9.2.{build}
install: 
  - cinst -y pester

test_script:
    - ps: |
        Import-Module 'C:\projects\cidney\cidney.psd1' -force
        $result = Invoke-Pester -PassThru -ExcludeTag Incomplete
        if ($result.FailedCount -gt 0) { 
            throw "$($result.FailedCount) tests failed."
        }
   