#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
os: WMF 5
version: 0.9.2.{build}
install: 
  - cinst -y pester

build: false

test_script:
    - ps: |
        # I dont have credentials to access the appveyor machine this runs on. So instead of 
        # using the On: keyword to import the modules I import them directly in the Do: block
        #
        Import-Module 'C:\projects\cidney\cidney.psd1' -force
        pipeline: CidneyBuild {
            Stage: Pester {
                Do: { Import-Module 'C:\projects\cidney\cidney.psd1'; Invoke-Pester -Script 'C:\projects\cidney\Tests\Pipeline.tests.ps1' }
                Do: { Import-Module 'C:\projects\cidney\cidney.psd1'; Invoke-Pester -Script 'C:\projects\cidney\Tests\Stage.tests.ps1' }
            }
        }

        Invoke-Cidney CidneyBuild -Verbose
