#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
os: WMF 5
version: 0.9.2.{build}
install: 
  - cinst -y pester

build: false

test_script:
    - ps: |
        Import-Module 'C:\projects\cidney\cidney.psd1' -force
        pipeline: CidneyBuild {
            Stage: Pester {
                On: $env:ComputerName {
                    Do: { Invoke-Pester -Script 'C:\projects\cidney\Tests\Pipeline.tests.ps1' }
                    Do: { Invoke-Pester -Script 'C:\projects\cidney\Tests\Stage.tests.ps1' }
                }
            }
        }

        Invoke-Cidney CidneyBuild -Verbose
