#
# Module manifest for module 'Cidney'
#
# Generated by: Robert Kozak
#
# Generated on: 3/4/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Cidney.psm1'

# Version number of this module.
ModuleVersion = '0.0.0.9'

# ID used to uniquely identify this module
GUID = '95f1121c-d1c5-4fc1-89c0-5da6e5cc2082'

# Author of this module
Author = 'Robert Kozak'

# Copyright statement for this module
Copyright = '(c) 2016 Robert Kozak. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This module defines a DSL for doing pipelines and stages for Continuous Integration and Deployment'

FunctionsToExport = 'Pipeline:','Stage:','Do:', 'Register-JobCommand', 'Get-RegisteredJobCommand', 'Get-RegisteredJobModule'
# Modules that must be imported into the global environment prior to importing this module
#RequiredModules = @('PoshRSJob')

# List of all files packaged with this module
FileList = '.\Keywords\Pipeline.ps1', '.\Keywords\Stage.ps1', '.\Keywords\On.ps1', '.\Keywords\Do.ps1'

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''

}

